### ISSUE TITLE
a long list of machine learning resources

### ISSUE THREAD

**Issue by nyurik** [awesome-rust-com/awesome-rust#20]
There is a [vaaaaanquish/Awesome-Rust-MachineLearning](https://github.com/vaaaaanquish/Awesome-Rust-MachineLearning) -- a long list of the relatively recent Rust resources. Is there a way to mention that in the list?  I am not sure if its a good idea to just copy all individual resources

**Comment by wujunze** [comment]
Hello, you can submit PR to create a new category
